### PR TITLE
Fix coverage

### PR DESCRIPTION
**Pull request by TomasVotruba**
This can be restored then.

Ref #37, #41, #42

### CODE REVIEW

**Comment by Ocramius** [comment]
Dang, I just submitted #44 :X

**Comment by TomasVotruba** [comment]
Great, just so it's finished :)

**Comment by Ocramius** [comment]
@TomasVotruba sorry for always stumbling on your work :S

**Comment by TomasVotruba** [comment]
@Ocramius I fine :) all I want is work to be done, no matter who does it ;)

**Pull request closed without merging**
