### PR TITLE
Scrutinizer: fix phpcs command

### PR DESCRIPTION
**Pull request by TomasVotruba**
Looks like Scrutinizer's version of phpcs is outdated.

I tried with phpcs 2.3.4 and timeoutes too on some Squiz sniff.

With version 2.5 all passes well. Probably it has bug fixed.

Ref https://github.com/Ocramius/PSR7Session/pull/37#issuecomment-164752245

### CODE REVIEW

**Comment by Ocramius** [comment]
> Configuration was invalid: Unrecognized option "test_command" under "{root}.tools.php_code_sniffer"

b8b627

**Comment by TomasVotruba** [comment]
Okay. So it looks like Scrutinizer [has only PHP 5.5 version](https://scrutinizer-ci.com/g/Ocramius/PSR7Session/inspections/fd62fa84-a4b2-4c85-80df-9136814b0375).

Thus:

- installing dependencies doesn't work
- own phpcs cannot be installed
- bugged phpcs has to be used

**Comment by TomasVotruba** [comment]
Mmm, it seems like for tests and for analysis, there are different PHP versions.

Tests passes, yet analysis fails.

Any ideas?

**Comment by Ocramius** [comment]
Nope, gotta poke @schmittjoh, I suppose :P

**Comment by lcobucci** [comment]
My config file is working with PHP 7
https://github.com/lcobucci/jwt/blob/master/.scrutinizer.yml 
https://scrutinizer-ci.com/g/lcobucci/jwt/inspections/dcc042c6-5cba-4b4a-b9ae-e765c99d6f6

**Comment by TomasVotruba** [comment]
@lcobucci Thanks for sharing. Yet referenced test is empty.

@Ocramius  

Ref to code-coverage: https://scrutinizer-ci.com/docs/build/code_coverage

>  This guide details how to generate code coverage when using Scrutinizer as your CI service (**paid plans only**). Please refer to sending external code coverage if you are using Scrutinizer for automated code reviews only.

It looks like the external coverage is the only way. Did you made it work somewhere else?

**Comment by Ocramius** [comment]
@TomasVotruba ProxyManager has a cotrect setup for external coverage submission

**Comment by TomasVotruba** [comment]
@Ocramius I meant for Scrutinizer internal coverage, as it's setup here.

For external I already sent [PR](https://github.com/Ocramius/PSR7Session/pull/37/files). What needs to be done then?

**Comment by Ocramius** [comment]
@TomasVotruba maybe try disabling phpcs entirely?

**Comment by Ocramius** [comment]
I disabled PHPCS in the scrutinizer-ci runs, closing here therefore.

Thanks @TomasVotruba!

**Comment by TomasVotruba** [comment]
Thank you

**Pull request closed without merging**
